from pyqtgraph import PlotWidget
from PyQt5 import QtCore,  QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(1030, 730)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_frame = QtWidgets.QFrame(self.centralwidget)
        self.btn_frame.setGeometry(QtCore.QRect(10, 680, 1021, 80))
        self.btn_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.btn_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.btn_frame.setObjectName("btn_frame")
        self.layoutWidget = QtWidgets.QWidget(self.btn_frame)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 10, 1011, 30))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.selectFolder_label = QtWidgets.QLabel(self.layoutWidget)
        self.selectFolder_label.setObjectName("selectFolder_label")
        self.horizontalLayout.addWidget(self.selectFolder_label)
        self.directoryPath_lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.directoryPath_lineEdit.setReadOnly(True)
        self.directoryPath_lineEdit.setObjectName("directoryPath_lineEdit")
        self.horizontalLayout.addWidget(self.directoryPath_lineEdit)
        self.selectFolder_toolButton = QtWidgets.QToolButton(self.layoutWidget)
        self.selectFolder_toolButton.setObjectName("selectFolder_toolButton")
        self.horizontalLayout.addWidget(self.selectFolder_toolButton)
        spacerItem = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.start_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.start_btn.setObjectName("start_btn")
        self.horizontalLayout.addWidget(self.start_btn)
        self.stop_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.stop_btn.setObjectName("stop_btn")
        self.horizontalLayout.addWidget(self.stop_btn)
        self.plot_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.plot_btn.setObjectName("plot_btn")
        self.horizontalLayout.addWidget(self.plot_btn)
        self.export_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.export_btn.setObjectName("export_btn")
        self.horizontalLayout.addWidget(self.export_btn)
        self.clear_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.clear_btn.setObjectName("clear_btn")
        self.horizontalLayout.addWidget(self.clear_btn)
        self.folder_tree_frame = QtWidgets.QFrame(self.centralwidget)
        self.folder_tree_frame.setGeometry(QtCore.QRect(0, 0, 271, 671))
        self.folder_tree_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.folder_tree_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.folder_tree_frame.setObjectName("folder_tree_frame")
        self.layoutWidget1 = QtWidgets.QWidget(self.folder_tree_frame)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 10, 261, 661))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.files_label = QtWidgets.QLabel(self.layoutWidget1)
        self.files_label.setObjectName("files_label")
        self.verticalLayout_2.addWidget(self.files_label)
        self.folder_tree = QtWidgets.QTreeView(self.layoutWidget1)
        self.folder_tree.setObjectName("folder_tree")
        self.verticalLayout_2.addWidget(self.folder_tree)
        self.status_lineEdit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.status_lineEdit.setReadOnly(True)
        self.status_lineEdit.setObjectName("status_lineEdit")
        self.verticalLayout_2.addWidget(self.status_lineEdit)
        self.plot_frame = QtWidgets.QFrame(self.centralwidget)
        self.plot_frame.setGeometry(QtCore.QRect(270, 10, 761, 661))
        self.plot_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.plot_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.plot_frame.setObjectName("plot_frame")
        self.layoutWidget2 = QtWidgets.QWidget(self.plot_frame)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 20, 741, 641))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.plot_tip_temp = PlotWidget(self.layoutWidget2)
        self.plot_tip_temp.setObjectName("plot_tip_temp")
        self.verticalLayout.addWidget(self.plot_tip_temp)
        self.plot_steam_temp = PlotWidget(self.layoutWidget2)
        self.plot_steam_temp.setObjectName("plot_steam_temp")
        self.verticalLayout.addWidget(self.plot_steam_temp)
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionSelect_Data_Repository = QtWidgets.QAction(MainWindow)
        self.actionSelect_Data_Repository.setObjectName(
            "actionSelect_Data_Repository")
        self.actionSelect_Data_Directory = QtWidgets.QAction(MainWindow)
        self.actionSelect_Data_Directory.setObjectName(
            "actionSelect_Data_Directory")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate(
            "MainWindow", "PILS Data Visualizer"))
        self.selectFolder_label.setText(_translate(
            "MainWindow", "Select PILS folder path:"))
        self.selectFolder_toolButton.setText(_translate("MainWindow", "..."))
        self.start_btn.setText(_translate("MainWindow", "Start Monitoring"))
        self.stop_btn.setText(_translate("MainWindow", "Stop Monitoring"))
        self.plot_btn.setText(_translate("MainWindow", "Plot Selected File "))
        self.export_btn.setText(_translate("MainWindow", "Export as xlsx"))
        self.clear_btn.setText(_translate("MainWindow", "Clear Plot"))
        self.files_label.setText(_translate("MainWindow", "Files:"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionSave.setText(_translate("MainWindow", "Export As xlsx"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionSelect_Data_Repository.setText(
            _translate("MainWindow", "Select Data Repository"))
        self.actionSelect_Data_Directory.setText(
            _translate("MainWindow", "Select Folder"))
